server {
    listen 80;
    server_name flowlane;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ $uri/index.html /index.html;
    }

    error_page 404 /index.html;
}