const MAX_SLUG_WORDS = 4;

/**
 * Matches a Jira-style ticket key such as "PRJ-456" (letters/digits, hyphen,
 * digits). Case is preserved so keys round-trip through branch names.
 */
const PROJECT_KEY_RE = /^[A-Za-z][A-Za-z0-9]*-[0-9]+$/;

/**
 * Generates a git branch name from a ticket ID and title.
 * Only the first MAX_SLUG_WORDS words of the title are used.
 *
 * Examples:
 *   generateBranchName('123',      'Fix login button')          → '123-fix-login-button'
 *   generateBranchName('PROJ-456', 'Add dark mode')             → 'PROJ-456-add-dark-mode'
 *   generateBranchName('789',      'A very long title with many words here')
 *                                                                → '789-a-very-long-title'
 */
export function generateBranchName(ticketId: string, title: string): string {
  const words = title
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')   // drop special chars except hyphens
    .trim()
    .split(/\s+/)
    .filter(Boolean);

  const slug = words
    .slice(0, MAX_SLUG_WORDS)
    .join('-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

  // Preserve Jira key case (e.g. "PRJ-456"); lower numeric-only IDs.
  const idPart = PROJECT_KEY_RE.test(ticketId.trim())
    ? ticketId.trim()
    : ticketId.toLowerCase().replace(/\s+/g, '-');

  return `${idPart}-${slug}`;
}

/** Returns true when the title has more words than the branch slug limit. */
export function titleIsTruncated(title: string): boolean {
  return title.trim().split(/\s+/).filter(Boolean).length > MAX_SLUG_WORDS;
}

/**
 * Extracts a ticket ID from the current git branch name.
 *
 * Supports both shapes generated by `generateBranchName`:
 *   '123-fix-login-button'     → '123'
 *   'PROJ-456-add-dark-mode'   → 'PROJ-456'
 *   'proj-456-add-dark-mode'   → 'proj-456'  (case preserved as found)
 *
 * Returns null if neither a project key nor a numeric ID can be parsed.
 */
export function ticketIdFromBranch(branch: string): string | null {
  // Jira-style key: ABC-123 (letters/digits-hyphen-digits).
  const keyMatch = branch.match(/^([A-Za-z][A-Za-z0-9]*-[0-9]+)(?:-|$)/);
  if (keyMatch) return keyMatch[1];

  // Azure DevOps work item IDs are purely numeric — match leading digits.
  const match = branch.match(/^(\d+)(?:-|$)/);
  if (match) return match[1];

  return null;
}
